<%@ Page Title="Modules" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Module.aspx.cs" Inherits="ADbSD_Coursework_I.WebForm5" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="container">
        <div><h3>Module</h3></div>
        <div>
            <div class="form-group mb-2">
                <asp:Label ID="idLBL" runat="server" Text="Module Code"></asp:Label>
                <asp:TextBox ID="idTB" runat="server" CssClass="form-control"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="idTB" ForeColor="#FF6666"></asp:RequiredFieldValidator>
            </div>
            
            <div class="form-group mb-2">
                <asp:Label ID="moduleNameLBL" runat="server" Text="Module Name"></asp:Label>
                <asp:TextBox ID="moduleNameTB" runat="server" CssClass="form-control"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="moduleNameTB" ForeColor="#FF6666"></asp:RequiredFieldValidator>
            </div>

            <div class="form-group mb-2">
                <asp:Label ID="creditHourLBL" runat="server" Text="Credit Hour"></asp:Label>
                <asp:TextBox ID="creditHourTB" runat="server" CssClass="form-control"></asp:TextBox>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" Display="Dynamic" ErrorMessage="This Field is Required!" ControlToValidate="creditHourTB" ForeColor="#FF6666"></asp:RequiredFieldValidator>
                <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" Display="Dynamic" ErrorMessage="Only Numbers Allowed!" ControlToValidate="creditHourTB" ForeColor="#FF6666" ValidationExpression="\d+"></asp:RegularExpressionValidator>
            </div>

            <div class="form-group mb-2">
                <asp:Button ID="submitModuleBTN" runat="server" Text="Submit" CssClass="btn btn-primary" OnClick="submitModuleBTN_Click"/>
            </div>
        </div>
        <div>

            <asp:GridView 
                ID="moduleGV" 
                runat="server" 
                CssClass="table" 
                DataKeyNames="module_code" 
                OnRowEditing="OnRowEditing"
                OnRowCancelingEdit="OnRowCancelEditing"
                OnRowDeleting="OnRowDeleting" 
                EmptyDataText="No Record Has Been Added!" 
                AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" 
                CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>

        </div>
    </div>
</asp:Content>
